.PHONY: all say_hello generate clean


all:= say_hello  generate

say_hello:
	@echo "Hello Mathworks"

generate:
	@echo "Creating empty text files..."
	touch file-{1..10}.txt

clean:
	@echo "Cleaning up..."
	rm *.txt

